In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read Footprint Data into notebook
footprint_data1 = pd.read_csv("Resources/countries.csv")
footprint_data1.head(1)

,Country,Region,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Cropland,Grazing Land,Forest Land,Fishing Water,Urban Land,Total Biocapacity,Biocapacity Deficit or Reserve,Earths Required,Countries Required,Data Quality
0,Afghanistan,Middle East/Central Asia,29.82,0.46,$614.66,0.3,0.2,0.08,0.18,0.0,...,0.24,0.2,0.02,0.0,0.04,0.5,-0.3,0.46,1.6,6

In [3]:
#Change names of Countries to match the Country names in the happiness data
replacements = {'Country': {
r'Libyan Arab Jamahiriya':'Libya',
r'Macedonia TFYR':'Macedonia',
r'Russian Federation':'Russia',
r'Syrian Arab Republic':'Syria',
r'Tanzania, United Republic of':'Tanzania',
r'United States of America':'United States',
r'Venezuela, Bolivarian Republic of':'Venezuela'}}

footprint_data1.replace(replacements, regex=True, inplace=True)

footprint_data1.head(1)

,Country,Region,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Cropland,Grazing Land,Forest Land,Fishing Water,Urban Land,Total Biocapacity,Biocapacity Deficit or Reserve,Earths Required,Countries Required,Data Quality
0,Afghanistan,Middle East/Central Asia,29.82,0.46,$614.66,0.3,0.2,0.08,0.18,0.0,...,0.24,0.2,0.02,0.0,0.04,0.5,-0.3,0.46,1.6,6

In [4]:
#Read Happiness data into notebook
Happiness_data1 = pd.read_csv("Resources/2016.csv")
Happiness_data1.head(1)

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.46,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939

In [5]:
#Merge Happiness and Footprint data
merge1 = footprint_data1.merge(Happiness_data1, left_on='Country', right_on='Country')
merge1

,Country,Region_x,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Afghanistan,Middle East/Central Asia,29.82,0.460000,$614.66,0.30,0.20,0.08,0.18,0.00,...,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
1,Albania,Northern/Eastern Europe,3.16,0.730000,"$4,534.37",0.78,0.22,0.25,0.87,0.02,...,4.655,4.546,4.764,0.95530,0.50163,0.73007,0.31866,0.05301,0.16840,1.92816
2,Algeria,Africa,38.48,0.730000,"$5,430.57",0.60,0.16,0.17,1.14,0.01,...,6.355,6.227,6.483,1.05266,0.83309,0.61804,0.21006,0.16157,0.07044,3.40904
3,Angola,Africa,20.82,0.520000,"$4,665.91",0.33,0.15,0.12,0.20,0.09,...,3.866,3.753,3.979,0.84731,0.66366,0.04991,0.00589,0.08434,0.12071,2.09459
4,Argentina,Latin America,41.09,0.830000,"$13,540.00",0.78,0.79,0.29,1.08,0.10,...,6.650,6.560,6.740,1.15137,1.06612,0.69711,0.42284,0.07296,0.10989,3.12985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,Uzbekistan,Middle East/Central Asia,28.54,0.670000,"$1,560.85",0.62,0.13,0.08,1.41,0.00,...,5.987,5.896,6.078,0.73591,1.16810,0.50163,0.60848,0.28333,0.34326,2.34638
134,Venezuela,Latin America,29.96,0.763846,"$10,237.80",0.45,0.74,0.12,2.13,0.09,...,6.084,5.973,6.195,1.13367,1.03302,0.61904,0.19847,0.08304,0.04250,2.97468
135,Yemen,Middle East/Central Asia,23.85,0.500000,"$1,302.30",0.34,0.14,0.04,0.42,0.04,...,3.724,3.621,3.827,0.57939,0.47493,0.31048,0.22870,0.05892,0.09821,1.97295
136,Zambia,Africa,14.08,0.580000,"$1,740.64",0.19,0.18,0.33,0.24,0.01,...,4.795,4.645,4.945,0.61202,0.63760,0.23573,0.42662,0.11479,0.17866,2.58991
137,Zimbabwe,Africa,13.72,0.490000,$865.91,0.20,0.32,0.29,0.53,0.01,...,4.193,4.101,4.285,0.35041,0.71478,0.15950,0.25429,0.08582,0.18503,2.44270

In [6]:
#Drop the duplicate country column
merge2 = merge1.drop(merge1.columns[-1],1)
merge2.head(1)

,Country,Region_x,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Afghanistan,Middle East/Central Asia,29.82,0.46,$614.66,0.3,0.2,0.08,0.18,0.0,...,154,3.36,3.288,3.432,0.38227,0.11037,0.17344,0.1643,0.07112,0.31268

In [7]:
#Output to excel
#merge2.to_excel("output3.xlsx")

In [8]:
merge2.drop(['Region_x','Cropland Footprint','Grazing Footprint','Forest Footprint','Carbon Footprint','Fish Footprint','Cropland','Grazing Land','Forest Land','Fishing Water','Urban Land','Data Quality','Lower Confidence Interval','Upper Confidence Interval'],axis=1, inplace=True)

In [9]:
merge2

,Country,Population (millions),HDI,GDP per Capita,Total Ecological Footprint,Total Biocapacity,Biocapacity Deficit or Reserve,Earths Required,Countries Required,Region_y,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Afghanistan,29.82,0.460000,$614.66,0.79,0.50,-0.30,0.46,1.60,Southern Asia,154,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268
1,Albania,3.16,0.730000,"$4,534.37",2.21,1.18,-1.03,1.27,1.87,Central and Eastern Europe,109,4.655,0.95530,0.50163,0.73007,0.31866,0.05301,0.16840
2,Algeria,38.48,0.730000,"$5,430.57",2.12,0.59,-1.53,1.22,3.61,Middle East and Northern Africa,38,6.355,1.05266,0.83309,0.61804,0.21006,0.16157,0.07044
3,Angola,20.82,0.520000,"$4,665.91",0.93,2.55,1.61,0.54,0.37,Sub-Saharan Africa,141,3.866,0.84731,0.66366,0.04991,0.00589,0.08434,0.12071
4,Argentina,41.09,0.830000,"$13,540.00",3.14,6.92,3.78,1.82,0.45,Latin America and Caribbean,26,6.650,1.15137,1.06612,0.69711,0.42284,0.07296,0.10989
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,Uzbekistan,28.54,0.670000,"$1,560.85",2.32,0.92,-1.40,1.34,2.52,Central and Eastern Europe,49,5.987,0.73591,1.16810,0.50163,0.60848,0.28333,0.34326
134,Venezuela,29.96,0.763846,"$10,237.80",3.57,2.78,-0.79,2.06,1.28,Latin America and Caribbean,44,6.084,1.13367,1.03302,0.61904,0.19847,0.08304,0.04250
135,Yemen,23.85,0.500000,"$1,302.30",1.03,0.50,-0.53,0.59,2.06,Middle East and Northern Africa,147,3.724,0.57939,0.47493,0.31048,0.22870,0.05892,0.09821
136,Zambia,14.08,0.580000,"$1,740.64",0.99,2.23,1.24,0.57,0.44,Sub-Saharan Africa,106,4.795,0.61202,0.63760,0.23573,0.42662,0.11479,0.17866
137,Zimbabwe,13.72,0.490000,$865.91,1.37,0.62,-0.75,0.79,2.20,Sub-Saharan Africa,131,4.193,0.35041,0.71478,0.15950,0.25429,0.08582,0.18503

In [14]:
merge2.to_csv('Resources/Merged_cols_selected.csv')

In [ ]:
#QUESTION   
merge2.groupby('Country')[['Happiness Rank','Economy (GDP per Capita)']].corr()

In [ ]:
# Correlation between Happiness Ranking and GDP
merge2[['Happiness Rank','Economy (GDP per Capita)']].corr()

In [ ]:
#HappGDP_std = merge2.groupby('Country')['Economy (GDP per Capita)'].var()
#HappGDP_std
#np.std(merge2['Economy (GDP per Capita)'])

In [ ]:
merge2[['Happiness Rank','Population (millions)']].corr()

In [ ]:
merge2[['Happiness Rank','Total Ecological Footprint']].corr()

In [ ]:
merge2[['Happiness Rank','Total Biocapacity']].corr()

In [ ]:
merge2[['Happiness Rank','Family']].corr()

In [ ]:
merge2[['Happiness Rank','Health (Life Expectancy)']].corr()

In [ ]:
merge2[['Happiness Rank','Freedom']].corr()

In [ ]:
merge2[['Happiness Rank','Generosity']].corr()

In [ ]:
import seaborn as sns
sns.lmplot(x='Economy (GDP per Capita)', y='Happiness Rank', data=merge2)

In [ ]:
# gdpsort.to_excel('gdpsort.xlsx')